apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu-usuario/argocd-examples
    targetRevision: main
    path: appsets/ # Ruta donde se encuentran los ApplicationSets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
